# Autogenerated Makefile; DO NOT MODIFY!
#
# Created by: AustinGarrick1818
# Script version: v0.0.2-alpha

SRC := pkg.c utils.c
OBJ := $(SRC:.c=.o)
MODULE := pkg

CC := /usr/bin/gcc
CC_STRIP := /usr/bin/strip

CFLAGS := -Os -Wall -Wextra -lcrypt -pthread

all: $(MODULE)

%.o: %.c
	$(CC) -c -o $@ $< $(CFLAGS)

$(MODULE): $(OBJ)
	$(CC) -o $@ $^ $(CFLAGS) $(LDFLAGS)

strip:
	$(CC_STRIP) --strip-unneeded $(MODULE)
	$(CC_STRIP) --strip-debug $(MODULE)

clean:
	rm -f *.o
	rm -f $(MODULE)
