# Autogenerated Makefil; DO NOT MODIFY!
#
# Created by: MasterHugeD
# Script version: v0.0.1-alpha

SRC := pkg.c
OBJ := $(SRC:.c=.o)
MODULE := pkg

CC := /usr/bin/arm-linux-gnueabi-gcc
CC_STRIP := /usr/bin/arm-linux-gnueabi-strip

CFLAGS := -Os -Wall -Wextra -lcrypt -lz -pthread

all: $(MODULE)

%.o: %.c
	$(CC) -c -o $@ $< $(CFLAGS)

$(MODULE): $(OBJ)
	$(CC) -o $@ $^ $(CFLAGS) $(LDFLAGS)

strip:
	$(CC_STRIP) --strip-unneeded $(MODULE)
	$(CC_STRIP) --strip-debug $(MODULE)

clean:
	rm -f *.o
	rm -f $(MODULE)
